### ISSUE TITLE
Table "fileupload" cannot be found in the database.

### ISSUE THREAD

**Issue by mexiter** [jetherton/fileupload#1]
Hi 
I am using ushahidi version 2.7. I installed and activated the plugin successfully but when I upload a file to a page it gives me this error:
Table "fileupload" cannot be found in the database. Please make sure you are using the latest version of the database for this version of Ushahidi.

Do you think it works with version 2.7  web platform.

**Comment by jetherton** [comment]
Hey,

I'm afraid not. I haven't worked on the file upload plugin in a long time.

**Comment by mexiter** [comment]
Hi jetherton,

I found a solution. 
I created the table manually from MySQL, and it works. 

Thank you for your response
